### ISSUE TITLE
Vocal file still contains background music

### ISSUE THREAD

**Issue by spoonwep** [karaokenerds/python-audio-separator#7] opened 2023-08-07 10:29 UTC
I tried to run the command:
`audio-separator test.mp3 --log_level debug --model_file_dir PATHTOMODELS --model_name UVR-MDX-NET-Inst_HQ_1`
It saved two files, the vocals file still contains background music while the instrumental file works perfect.
But if I add the `--single_stem vocals`, it doesn't contain background music. Is this a bug?

**Comment by beveradb** [comment] 2023-08-11 21:00
Hey, thanks for the report!
I'm not able to reproduce though - these are the results I get, testing with the default model (`UVR_MDXNET_KARA_2`), and also `UVR-MDX-NET-Inst_HQ_1` and `UVR-MDX-NET-Inst_HQ_3`

```
➜ audio-separator test.mp3 --log_level debug
2023-08-11 15:42:39.627 - INFO - cli - Separator beginning with input file: test.mp3
2023-08-11 15:42:39.628 - DEBUG - separator - Separator instantiating with input file: test.mp3, model_name: UVR_MDXNET_KARA_2, output_dir: None, use_cuda: False, output_format: MP3
2023-08-11 15:42:39.628 - DEBUG - separator - Normalization enabled, waveform will be normalized to max amplitude of 1.0 to avoid clipping.
2023-08-11 15:42:39.628 - DEBUG - separator - Denoising enabled, model will be run twice to reduce noise in output audio.
2023-08-11 15:42:39.628 - DEBUG - separator - Running in CPU mode
2023-08-11 15:42:39.628 - DEBUG - separator - Reading model settings...
2023-08-11 15:42:39.658 - DEBUG - separator - Model /tmp/audio-separator-models/UVR_MDXNET_KARA_2.onnx has hash 1d64a6d2c30f709b8c9b4ce1366d96ee ...
2023-08-11 15:42:39.659 - DEBUG - separator - Set model data values: compensate = 1.065 primary_stem = Instrumental dim_f = 2048 dim_t = 256 n_fft = 5120
2023-08-11 15:42:39.659 - DEBUG - separator - Loading model...
2023-08-11 15:42:39.694 - INFO - separator - Running inference...
2023-08-11 15:42:40.167 - INFO - separator - Demixing...
2023-08-11 15:44:40.387 - INFO - separator - Saving Instrumental stem...
2023-08-11 15:44:40.406 - DEBUG - spec_utils - Normalization Set True: Input not above threshold for clipping. Max:0.9090502262115479
2023-08-11 15:44:41.339 - INFO - separator - Saving Vocals stem...
2023-08-11 15:44:44.069 - DEBUG - spec_utils - Normalization Set True: Input not above threshold for clipping. Max:0.9681385159492493
2023-08-11 15:44:44.088 - DEBUG - spec_utils - Normalization Set True: Primary source - Max:0.9681385159492493
2023-08-11 15:44:44.099 - DEBUG - spec_utils - Normalization Set True: Mixture - Max:1.0084656476974487
2023-08-11 15:44:45.055 - INFO - cli - Separation complete! Output file(s): test_(Instrumental)_UVR_MDXNET_KARA_2.mp3 test_(Vocals)_UVR_MDXNET_KARA_2.mp3

➜ audio-separator test.mp3 --log_level debug --model_name UVR-MDX-NET-Inst_HQ_1
2023-08-11 15:31:50.394 - INFO - cli - Separator beginning with input file: test.mp3
2023-08-11 15:31:50.394 - DEBUG - separator - Separator instantiating with input file: test.mp3, model_name: UVR-MDX-NET-Inst_HQ_1, output_dir: None, use_cuda: False, output_format: MP3
2023-08-11 15:31:50.394 - DEBUG - separator - Normalization enabled, waveform will be normalized to max amplitude of 1.0 to avoid clipping.
2023-08-11 15:31:50.394 - DEBUG - separator - Denoising enabled, model will be run twice to reduce noise in output audio.
2023-08-11 15:31:50.394 - DEBUG - separator - Running in CPU mode
2023-08-11 15:31:50.394 - DEBUG - separator - Model not found at path /tmp/audio-separator-models/UVR-MDX-NET-Inst_HQ_1.onnx, downloading...
100% [........................................................................] 66759214 / 667592142023-08-11 15:32:10.602 - DEBUG - separator - Reading model settings...
2023-08-11 15:32:10.641 - DEBUG - separator - Model /tmp/audio-separator-models/UVR-MDX-NET-Inst_HQ_1.onnx has hash 291c2049608edb52648b96e27eb80e95 ...
2023-08-11 15:32:10.646 - DEBUG - separator - Set model data values: compensate = 1.035 primary_stem = Instrumental dim_f = 3072 dim_t = 256 n_fft = 6144
2023-08-11 15:32:10.646 - DEBUG - separator - Loading model...
2023-08-11 15:32:10.704 - INFO - separator - Running inference...
2023-08-11 15:32:13.121 - INFO - separator - Demixing...
2023-08-11 15:35:23.867 - INFO - separator - Saving Instrumental stem...
2023-08-11 15:35:23.888 - DEBUG - spec_utils - Normalization Set True: Input not above threshold for clipping. Max:0.9418708086013794
2023-08-11 15:35:24.862 - INFO - separator - Saving Vocals stem...
2023-08-11 15:35:27.982 - DEBUG - spec_utils - Normalization Set True: Input not above threshold for clipping. Max:0.9748362302780151
2023-08-11 15:35:27.994 - DEBUG - spec_utils - Normalization Set True: Primary source - Max:0.9748362302780151
2023-08-11 15:35:28.010 - DEBUG - spec_utils - Normalization Set True: Mixture - Max:1.0048141479492188
2023-08-11 15:35:28.988 - INFO - cli - Separation complete! Output file(s): test_(Instrumental)_UVR-MDX-NET-Inst_HQ_1.mp3 test_(Vocals)_UVR-MDX-NET-Inst_HQ_1.mp3

➜ audio-separator test.mp3 --log_level debug --model_name UVR-MDX-NET-Inst_HQ_3
2023-08-11 15:37:38.131 - INFO - cli - Separator beginning with input file: test.mp3
2023-08-11 15:37:38.131 - DEBUG - separator - Separator instantiating with input file: test.mp3, model_name: UVR-MDX-NET-Inst_HQ_3, output_dir: None, use_cuda: False, output_format: MP3
2023-08-11 15:37:38.131 - DEBUG - separator - Normalization enabled, waveform will be normalized to max amplitude of 1.0 to avoid clipping.
2023-08-11 15:37:38.131 - DEBUG - separator - Denoising enabled, model will be run twice to reduce noise in output audio.
2023-08-11 15:37:38.131 - DEBUG - separator - Running in CPU mode
2023-08-11 15:37:38.131 - DEBUG - separator - Model not found at path /tmp/audio-separator-models/UVR-MDX-NET-Inst_HQ_3.onnx, downloading...
100% [........................................................................] 66759214 / 667592142023-08-11 15:37:49.787 - DEBUG - separator - Reading model settings...
2023-08-11 15:37:49.829 - DEBUG - separator - Model /tmp/audio-separator-models/UVR-MDX-NET-Inst_HQ_3.onnx has hash 55657dd70583b0fedfba5f67df11d711 ...
2023-08-11 15:37:49.839 - DEBUG - separator - Set model data values: compensate = 1.022 primary_stem = Instrumental dim_f = 3072 dim_t = 256 n_fft = 6144
2023-08-11 15:37:49.839 - DEBUG - separator - Loading model...
2023-08-11 15:37:49.886 - INFO - separator - Running inference...
2023-08-11 15:37:50.768 - INFO - separator - Demixing...
2023-08-11 15:41:01.428 - INFO - separator - Saving Instrumental stem...
2023-08-11 15:41:01.449 - DEBUG - spec_utils - Normalization Set True: Input not above threshold for clipping. Max:0.9526664614677429
2023-08-11 15:41:02.434 - INFO - separator - Saving Vocals stem...
2023-08-11 15:41:05.562 - DEBUG - spec_utils - Normalization Set True: Input not above threshold for clipping. Max:0.9736250638961792
2023-08-11 15:41:05.573 - DEBUG - spec_utils - Normalization Set True: Primary source - Max:0.9736250638961792
2023-08-11 15:41:05.585 - DEBUG - spec_utils - Normalization Set True: Mixture - Max:1.0048141479492188
2023-08-11 15:41:06.549 - INFO - cli - Separation complete! Output file(s): test_(Instrumental)_UVR-MDX-NET-Inst_HQ_3.mp3 test_(Vocals)_UVR-MDX-NET-Inst_HQ_3.mp3

```

I've attached the input and output files here too so you can have a listen and try for yourself;

[test-Inst_HQ_1.zip](https://github.com/karaokenerds/python-audio-separator/files/12325109/test-Inst_HQ_1.zip)

If you're able to share a test file and your output logs with me, I might be able to spot something else and hopefully reproduce for myself - maybe there's something weird with the way the model processes your specific track?

Have you tried any other models with the same track?

**Comment by spoonwep** [comment] 2023-08-13 04:21
thank you for the reply.
here are my example files:

https://drive.google.com/file/d/1EnZHNlthf2bV4b-ezCR1U374yCuOnhTl/view

and here is my log:
```
audio-separator test.mp3 --log_level debug --model_file_dir /Users/apple/Downloads/ai/python-audio-separator/models --model_name UVR-MDX-NET-Inst_HQ_3
2023-08-13 12:09:35.427 - INFO - cli - Separator beginning with input file: test.mp3
2023-08-13 12:09:35.427 - DEBUG - separator - Separator instantiating with input file: test.mp3, model_name: UVR-MDX-NET-Inst_HQ_3, output_dir: None, use_cuda: False, output_format: FLAC
2023-08-13 12:09:35.427 - DEBUG - separator - Normalization enabled, waveform will be normalized to max amplitude of 1.0 to avoid clipping.
2023-08-13 12:09:35.427 - DEBUG - separator - Denoising enabled, model will be run twice to reduce noise in output audio.
2023-08-13 12:09:35.427 - DEBUG - separator - Running in CPU mode
2023-08-13 12:09:35.427 - DEBUG - separator - Reading model settings...
2023-08-13 12:09:35.447 - DEBUG - separator - Model /Users/apple/Downloads/ai/python-audio-separator/models/UVR-MDX-NET-Inst_HQ_3.onnx has hash 55657dd70583b0fedfba5f67df11d711 ...
2023-08-13 12:09:35.448 - DEBUG - separator - Set model data values: compensate = 1.022 primary_stem = Instrumental dim_f = 3072 dim_t = 256 n_fft = 6144
2023-08-13 12:09:35.449 - DEBUG - separator - Loading model...
2023-08-13 12:09:35.601 - INFO - separator - Running inference...
2023-08-13 12:09:36.094 - INFO - separator - Demixing...
2023-08-13 12:13:36.043 - INFO - separator - Saving Instrumental stem...
2023-08-13 12:13:36.077 - DEBUG - spec_utils - Normalization Set True: Input above threshold for clipping. Max:1.32501220703125
2023-08-13 12:13:36.077 - DEBUG - spec_utils - The result was normalized.
2023-08-13 12:13:37.267 - INFO - separator - Saving Vocals stem...
2023-08-13 12:13:40.879 - DEBUG - spec_utils - Normalization Set True: Primary source above threshold for clipping. Max:1.0219999551773071
2023-08-13 12:13:40.879 - DEBUG - spec_utils - Normalization Set True: Mixture above threshold for clipping. Max:1.071467638015747
2023-08-13 12:13:40.879 - DEBUG - spec_utils - The result was normalized.
2023-08-13 12:13:40.903 - DEBUG - spec_utils - Normalization Set True: Primary source - Max:1.0
2023-08-13 12:13:40.921 - DEBUG - spec_utils - Normalization Set True: Mixture - Max:1.0484027862548828
2023-08-13 12:13:42.135 - INFO - cli - Separation complete! Output file(s): test_(Instrumental)_UVR-MDX-NET-Inst_HQ_3.flac test_(Vocals)_UVR-MDX-NET-Inst_HQ_3.flac
```

**Comment by beveradb** [comment] 2023-08-14 06:06
Thanks for the test file and logs!

So, I ran some tests with that test file, trying different models (especially a couple of models which are designed to prioritise better isolation of _vocals_ over isolation of _instrumental_ stems. My notes are below.

### Test 1 (both stems, denoiser enabled):
Initially I simply ran all each model with the default options (both stems, denoiser enabled).

UVR-MDX-NET-Inst_HQ_3:
`audio-separator test.mp3 --log_level debug --model_name UVR-MDX-NET-Inst_HQ_3`:
- `test_(Instrumental)_UVR-MDX-NET-Inst_HQ_3.flac` - Clean instrumental track, no vocals even in the chorus
- `test_(Vocals)_UVR-MDX-NET-Inst_HQ_3.flac` - Quiet instrumental background throughout (perhaps 30% of original volume) with prominent and clear vocals on top

UVR-MDX-NET-Voc_FT:
`audio-separator test.mp3 --log_level debug --model_name UVR-MDX-NET-Voc_FT`:
- `test_(Instrumental)_UVR-MDX-NET-Voc_FT.flac` - Clean instrumental track, no vocals even in the chorus
- `test_(Vocals)_UVR-MDX-NET-Voc_FT.flac` - Clean vocal track, no instrumental even in the chorus

UVR_MDXNET_KARA_2:
`audio-separator test.mp3 --log_level debug --model_name UVR_MDXNET_KARA_2`:
- `test_(Instrumental)_UVR_MDXNET_KARA_2.flac` - Clean instrumental track, plus faint support vocals at points, e.g. during the chorus at 02:58 and 04:35 
- `test_(Vocals)_UVR_MDXNET_KARA_2.flac` - Quiet instrumental background throughout (perhaps 30% of original volume) with prominent and clear vocals on top

Kim_Vocal_2:
`audio-separator test.mp3 --log_level debug --model_name Kim_Vocal_2`:
- `test_(Instrumental)_Kim_Vocal_2.flac` - Clean instrumental track, no vocals even in the chorus
- `test_(Vocals)_Kim_Vocal_2.flac` - Clean vocal track, no instrumental even in the chorus

### Test 2 (both stems, denoiser disabled):
This was just to test whether the quiet instrumental backing was also present in the vocal track for Inst_HQ_3 when denoising was disabled.

UVR-MDX-NET-Inst_HQ_3:
`audio-separator test.mp3 --log_level debug --model_name UVR-MDX-NET-Inst_HQ_3`:
- `test_(Instrumental)_UVR-MDX-NET-Inst_HQ_3.flac` - Clean instrumental track, no vocals even in the chorus
- `test_(Vocals)_UVR-MDX-NET-Inst_HQ_3.flac` - Quiet instrumental background throughout (perhaps 30% of original volume) with prominent and clear vocals on top

So, not caused by the denoise. Will disable denoiser for the next tests anyway for speed though, as I'm running on CPU.

### Test 3 (single stem vocals, denoiser disabled):
This was to compare what we get from each model in single stem mode vs. when we write both stems.

UVR-MDX-NET-Inst_HQ_3:
`audio-separator test.mp3 --log_level debug --model_name UVR-MDX-NET-Inst_HQ_3 --single_stem vocals --denoise false`
- `test_(Vocals)_UVR-MDX-NET-Inst_HQ_3.flac` - Mostly clean vocal track, very faint (maybe 1%) instrumentals in the chorus (e.g. 3:30) - this is confusing as the vocal track from the same model in test 1 had quiet instrumental background

UVR-MDX-NET-Voc_FT:
`audio-separator test.mp3 --log_level debug --model_name UVR-MDX-NET-Voc_FT --single_stem vocals --denoise false`
- `test_(Vocals)_UVR-MDX-NET-Voc_FT.flac` - Clean vocal track, no instrumental even in the chorus

UVR_MDXNET_KARA_2:
`audio-separator test.mp3 --log_level debug --model_name UVR_MDXNET_KARA_2 --single_stem vocals --denoise false`
- `test_(Vocals)_UVR_MDXNET_KARA_2.flac` - Clean vocal track, very faint (maybe 2%) instrumentals in the chorus (e.g. 3:30), some minor artefacts 

Kim_Vocal_2:
`audio-separator test.mp3 --log_level debug --model_name Kim_Vocal_2 --single_stem vocals --denoise false`
- `test_(Vocals)_Kim_Vocal_2.flac` - Clean vocal track, no instrumental even in the chorus

### Test 4 (single stem instrumental, denoiser disabled):
This was to continue comparing what we get from each model in single stem mode vs. when we write both stems.

UVR-MDX-NET-Inst_HQ_3:
`audio-separator test.mp3 --log_level debug --model_name UVR-MDX-NET-Inst_HQ_3 --single_stem instrumental --denoise false`
- `test_(Instrumental)_UVR-MDX-NET-Inst_HQ_3.flac` - Clean instrumental track, no vocals even in the chorus

UVR-MDX-NET-Voc_FT:
`audio-separator test.mp3 --log_level debug --model_name UVR-MDX-NET-Voc_FT --single_stem instrumental --denoise false`
- `test_(Instrumental)_UVR-MDX-NET-Voc_FT.flac` - Clean instrumental track, no vocals even in the chorus

UVR_MDXNET_KARA_2:
`audio-separator test.mp3 --log_level debug --model_name UVR_MDXNET_KARA_2 --single_stem instrumental --denoise false`
- `test_(Instrumental)_UVR_MDXNET_KARA_2.flac` - Clean instrumental track, plus faint support vocals at points, e.g. during the chorus at 02:58 and 04:35 

Kim_Vocal_2:
`audio-separator test.mp3 --log_level debug --model_name Kim_Vocal_2 --single_stem instrumental --denoise false`
- `test_(Instrumental)_Kim_Vocal_2.flac` - Clean instrumental track, no vocals even in the chorus

### Test 5 (test fix code branch, both stems, denoiser disabled):
This is essentially repeating Test 2 but with my new code branch which still runs the secondary demix even if only the primary stem is wanted.

UVR-MDX-NET-Inst_HQ_3:
`audio-separator test.mp3 --log_level debug --model_name UVR-MDX-NET-Inst_HQ_3 --denoise false`:
- `test_(Instrumental)_UVR-MDX-NET-Inst_HQ_3.flac` - Clean instrumental track, no vocals even in the chorus
- `test_(Vocals)_UVR-MDX-NET-Inst_HQ_3.flac` - Quiet instrumental background throughout (perhaps 30% of original volume) with prominent and clear vocals on top

### Test 6 (test fix code branch, single stem vocals, denoiser disabled):
This is essentially repeating Test 3 but with my new code branch which still runs the secondary demix even if only the primary stem is wanted.

UVR-MDX-NET-Inst_HQ_3:
`audio-separator test.mp3 --log_level debug --model_name UVR-MDX-NET-Inst_HQ_3 --single_stem vocals --denoise false`:
- `test_(Vocals)_UVR-MDX-NET-Inst_HQ_3.flac` - Quiet instrumental background throughout (perhaps 30% of original volume) with prominent and clear vocals on top

Ok, so yes, that means [this code logic](https://github.com/karaokenerds/python-audio-separator/commit/52fd80c37facf42e251d73f0a5ce64ba9228ff15) was at least the source of the inconsistency between single stem mode and outputting both stems at the same time.

I've "[fixed](https://github.com/karaokenerds/python-audio-separator/commit/52fd80c37facf42e251d73f0a5ce64ba9228ff15)" that in version `0.7.2`, which should be available with `pip install -U audio-separator`.

I guess it's debatable whether it's right to consider this "fixed" though, as the output from the UVR-MDX-NET-Inst_HQ_3 model still includes 30% instrumental in it's vocal output - but this makes the output at least _consistent_ between modes, which I feel is slightly more correct.

I'm not entirely sure what the best way to proceed is; I guess ideally we'd want the Vocal file output from the UVR-MDX-NET-Inst_HQ_3 model to not include any instrumentals, but the fact that there are other models here which already work perfectly (e.g. `UVR-MDX-NET-Voc_FT`) and provide that with the current code leaves me scratching my head a bit.

My test files are here by the way, though the archive is 700MB :sweat_smile: https://www.dropbox.com/s/f7e34vm59377coa/stem-split-testing.tar.xz?dl=0

I'll give this a bit more thought in the morning with a fresh pair of eyes and see if I can get to the bottom of it. Would appreciate your input too! :)

For now if it's a priority for your use case to get clean vocals, you'll probably get better results using a vocal-focused model, e.g. `UVR-MDX-NET-Voc_FT` or `Kim_Vocal_2`. I'm generally only interested in the instrumentals (I make karaoke videos) which is probably why I didn't notice this myself!

**Comment by hero-intelligent** [comment] 2023-08-29 03:43
Hello, guys, I'm a enthusiastic user of UVR5, and the models that are used here are provided by their team, not this project. And according to my experience, I'm sorry to tell that their models sometimes perform poorly when processing some songs, either vocal left in the instrument not separated, or instrument leaks out to vocal. The only solution may probably be continue to polishing the model, which is a huge work for UVR5 team, but not for this project here. It's a pity though, but the responsibility of this project is to polish the code and logic to make full use of each model, and test and choose which is the best model for the chosen song. We need to have patience for the development of models provided upstream. Best wishes.

**Comment by beveradb** [comment] 2023-09-12 07:27
While your statements are mostly correct there @hero-intelligent, I don't think this project needs to restrict itself to only work with models created by the UVR team - if somebody raised a PR here adding support for another model from elsewhere, or adding a new model directly to this project, I would be happy with that as it would reduce the dependency!

Also, the issue raised by @spoonwep in this thread was (I believe) fixed by [my commit](https://github.com/karaokenerds/python-audio-separator/commit/52fd80c37facf42e251d73f0a5ce64ba9228ff15) in version `0.7.2` and I've heard nothing back since, so I'm closing this as resolved.

**Closed by beveradb** 2023-09-12 07:27 UTC
