### ISSUE TITLE
some popping sound occurred

### ISSUE THREAD

**Issue by mc261670164** [karaokenerds/python-audio-separator#29] opened 2024-01-03 14:14 UTC
Hi,
   When I use the karaok_2 model to split the audio file, sometimes some popping sound will occur, but when I use the UVR app it dosent. I use the model with parameters like below:
model_name="UVR_MDXNET_KARA_2",
model_file_dir="./models",
normalization_enabled=False,
denoise_enabled=False

when I set all of the normalization_enabled and denoise_enabled to true, the vocals will include background music. Have you ever been in this situation？
The audio I used is in the attachement.

**Comment by mc261670164** [comment] 2024-01-03 14:16
[Uploading test.zip…]()

**Comment by mc261670164** [comment] 2024-01-03 15:05
And also when I using the UVR_MDXNET_KARA_2 and change the segment_size to 512, it will report an error： PermissionError: [Errno 13] Permission denied: 'E:\\Code\\test_projects\\python-audio-separator\\models\\tmpiq8r7y89'

**Comment by beveradb** [comment] 2024-01-03 22:26
Hey, thanks for the report, I'd like to reproduce but I wasn't able to download your file (the link in the previous message seems to just link back to this issue)

Please could you upload the input audio somewhere else? eg. https://www.file.io maybe

**Comment by mc261670164** [comment] 2024-01-04 06:30
@beveradb Thanks for your reply, you can get the file from this url: https://file.io/c459ip7Ms8Uf

**Comment by beveradb** [comment] 2024-01-04 07:00
Got it, thanks!

I think I've reproduced exactly what you're referring to - see my test files and logs here: https://www.dropbox.com/scl/fo/xa5ek50i8n6tgd8attbey/h?rlkey=uz4llpjlmakef76wurt4sg5vl&dl=0

Pretty certain it's about the normalization - that track has very high amplitude already so when the vocals are separated they're clipping as they're above the max amplitude possible:

<img width="763" alt="BEYOND 2024-01-04 00-53-28" src="https://github.com/karaokenerds/python-audio-separator/assets/757713/c54d1746-fbf1-492e-95c8-45446c775eb4">

That's something which should be resolved by the [normalization process](https://github.com/karaokenerds/python-audio-separator/blob/main/audio_separator/separator/spec_utils.py#L110) (so simply add `--normalize=True`) but I see what you mean in that with normalization enabled, the output vocal track has a lot more instrumental present.

There _shouldn't_ be any difference between audio-separator and UVR in theory, especially not after my latest round of syncing changes between the two, but I was able to reproduce the difference for sure.

I'll try and look into it later this week/this weekend when I next have some hobby project time.
Thanks for the report and sample file!

**Comment by beveradb** [comment] 2024-01-04 07:07
For what it's worth, if you pre-normalise the track e.g. in Audacity before running it through audio-separator, that resolves the issue too:

<img width="710" alt="BEYOND 2024-01-04 01-04-27" src="https://github.com/karaokenerds/python-audio-separator/assets/757713/496ee0b3-e2e7-4e70-9028-8f9f7c645dc6">
<img width="693" alt="BEYOND 2024-01-04 01-04-34" src="https://github.com/karaokenerds/python-audio-separator/assets/757713/24ecfd39-eb5d-45de-aaed-cd5ed1f6e626">

Here's an example of that:
https://www.dropbox.com/scl/fo/pcducqjxi0vi7jt8k2q0r/h?rlkey=82vlar15uuoffjwf4t6p8qjq7&dl=0

**Comment by mc261670164** [comment] 2024-01-04 12:29
Thanks very much and looking forward to your reply!

**Comment by beveradb** [comment] 2024-01-09 06:41
Hey @mc261670164 please could you upgrade to version `0.13.0` and try again?

I've replaced the `normalization_enabled` parameter with a `normalization_threshold` one, with a safer default of 0.9, and added a normalization step to the input mix before demixing, which should prevent any output from `audio-separator` from clipping (popping) ever again 😃 

I tested on your `BEYOND` input file and it worked well for me!

**Comment by mc261670164** [comment] 2024-01-09 15:31
Hey @beveradb thanks for your replay, I've got the latest code and tried it. I found that in this version of the separation results, the vocals would contain instrument, and the instrument would also contain vocals. I use it like below:
![1704814291706](https://github.com/karaokenerds/python-audio-separator/assets/30143189/180fac75-3682-4dc8-bb83-748b3e28a809)

**Comment by Subraiz** [comment] 2024-01-21 12:28
> Hey @mc261670164 please could you upgrade to version `0.13.0` and try again?
> 
> I've replaced the `normalization_enabled` parameter with a `normalization_threshold` one, with a safer default of 0.9, and added a normalization step to the input mix before demixing, which should prevent any output from `audio-separator` from clipping (popping) ever again 😃
> 
> I tested on your `BEYOND` input file and it worked well for me!

you are a god amongst mortals this helped me a bunch!

**Comment by beveradb** [comment] 2024-01-21 19:53
Thanks for the kind words @Subraiz 🙇 - would you be able to clarify how, though? 
Just to help me understand how users are using it; do you use `audio-separator` as a command-line tool or instantiate it from some other code? What parameters are you setting? 


And, @mc261670164 - "the vocals would contain instrument, and the instrument would also contain vocals" is kinda a different issue to the "popping" (normalization/amplitude clipping) issue you raised initially in this thread;

Were you experiencing that with that same test file you shared with me (`BEYOND`)? Because when I tested that with the latest `audio-separator` CLI and default parameters it worked pretty well in my opinion!

Please could you provide a test file demonstrating the issue, and tell me if you have the same issue when separating it with default CLI parameters?
Also, if you're trying to achieve clean instrumental audio without *any* vocals at all, the `UVR_MDXNET_KARA_2` model probably isn't ideal, as that is deliberately designed to leave backing vocals in and sometimes misidentifies those.

Try a model which is designed for pure instrumentals, e.g. `UVR-MDX-NET-Inst_HQ_3`

**Comment by beveradb** [comment] 2024-02-05 23:30
I haven't had a reply recently from anyone with a test audio file and I can't reproduce this any more in the latest version of audio-separator (version `0.14` or newer), so I'm going to close this.

If anyone still has an issue with the latest versions, please open a new issue, and share a sample audio file and the parameters you're using! 🙇

**Closed by beveradb** 2024-02-05 23:30 UTC
