### ISSUE TITLE
MDX23C compatibility

### ISSUE THREAD

**Issue by AWAS666** [karaokenerds/python-audio-separator#19] opened 2023-10-09 20:47 UTC
Hey good job on your tool, exactly what I was looking for.

Will there be support for MDX23C ?

It's rather new in uvr and seems to be a variation of mdx (comes in .onnx format) but seems to be really good.

UVR uses different classes for mdx and mdxc as they call it.

**Comment by beveradb** [comment] 2023-10-10 17:21
Hey, thanks 😄 

What exactly do you mean by support for it? If it's already an ONNX model it should already work - are you getting any error or something when you try it?

**Comment by beveradb** [comment] 2023-10-20 15:53
Ah, then my response is the same as this issue for now - https://github.com/karaokenerds/python-audio-separator/issues/18#issuecomment-1730702518

Basically, PRs and implementation support very much welcome, I'd be very happy to schedule a Zoom call and talk through the code / pair program with anyone interested in collaborating!

If nobody steps up to try and help with implementation though, I can't say I'm independently motivated to add support for more model types on my own as the tool already meets my own personal needs for now.

**Comment by beveradb** [comment] 2024-01-11 17:26
Closing as dupe of #18 to keep everything in one place - someone needs to implement support for the PTH and CKPT models in `audio-separator`, PRs very welcome and/or feel free to email me directly if anyone wants to work on it :)

**Closed by beveradb** 2024-01-11 17:26 UTC
Labels: enhancement, help wanted
